create table classrooms (id integer generated by default as identity, name varchar(50) not null, consultant_id integer, course_id integer, primary key (id));
create table classrooms_students (classrooms_id integer not null, students_id integer not null);
create table courses (id integer generated by default as identity, credits double, name varchar(50) not null, degree_id integer, primary key (id));
create table degrees (id integer generated by default as identity, name varchar(50) not null, primary key (id));
create table exam_answers (id integer generated by default as identity, change_date timestamp, creation_date date, finished boolean not null, exam_id integer not null, student_id integer not null, primary key (id));
create table exam_question_answers (id integer generated by default as identity, answer varchar(4000) not null, exam_answer_id integer not null, exam_question_id integer not null, primary key (id));
create table exam_question_option_answers (id integer generated by default as identity, answer varchar(4000) not null, is_selected boolean not null, exam_question_answer_id integer, exam_question_option_id integer, primary key (id));
create table exam_question_options (id integer generated by default as identity, is_rigth boolean not null, position integer, wording varchar(500) not null, exam_question_id integer, primary key (id));
create table exam_questions (id integer generated by default as identity, is_multiple_selection boolean not null, position integer, type varchar(25) not null, wording varchar(500) not null, exam_id integer, primary key (id));
create table exams (id integer generated by default as identity, change_date timestamp, creation_date date, deadline date, instructions varchar(500), name varchar(50) not null, publication_date timestamp, type varchar(25) not null, consultant_id integer not null, course_id integer not null, primary key (id));
create table groups (id integer generated by default as identity, name varchar(50) not null, classroom_id integer, primary key (id));
create table groups_students (groups_id integer not null, students_id integer not null);
create table student_option_answer_scores (exam_question_option_answer_id integer not null, student_id integer not null, score integer, primary key (exam_question_option_answer_id, student_id));
create table users (class varchar(31) not null, id integer generated by default as identity, dni varchar(9) not null, first_name varchar(50) not null, surname1 varchar(50), surname2 varchar(50), user_name varchar(50) not null, user_password varchar(50) not null, primary key (id));
alter table classrooms add constraint FK7lbt0l1u0tdl3herl3wxin8vs foreign key (consultant_id) references users;
alter table classrooms add constraint FKptrcjflhvj48duhcag4f3x9j0 foreign key (course_id) references courses;
alter table classrooms_students add constraint FK4qm2nt9roi9exg19i7ct4lyug foreign key (students_id) references users;
alter table classrooms_students add constraint FK1deyd4gk9oyhuq5715o9k2nfi foreign key (classrooms_id) references classrooms;
alter table courses add constraint FK1q2jh9x42qm5dspcsc6ux6rfe foreign key (degree_id) references degrees;
alter table exam_answers add constraint FKa5smxoto4oun5q5gffv7ly5yl foreign key (exam_id) references exams;
alter table exam_answers add constraint FK36fhn2x04ghokcj68si7iovhi foreign key (student_id) references users;
alter table exam_question_answers add constraint FKp9qast4xdo98rpy8mfg33djtg foreign key (exam_answer_id) references exam_answers;
alter table exam_question_answers add constraint FKax5lkfslgig12uhtorr1a3e9i foreign key (exam_question_id) references exam_questions;
alter table exam_question_option_answers add constraint FKhqr5lew83sp9g5d0752m9osmd foreign key (exam_question_answer_id) references exam_question_answers;
alter table exam_question_option_answers add constraint FKaoirvnctlkkhl0940vgvsurob foreign key (exam_question_option_id) references exam_question_options;
alter table exam_question_options add constraint FKn0j8vm7lf2vq9ie4q27046k4r foreign key (exam_question_id) references exam_questions;
alter table exam_questions add constraint FK5cd6sjmccb11rrwpyabyc81c0 foreign key (exam_id) references exams;
alter table exams add constraint FKm3adut716bdwmb3w0qkwcdo2k foreign key (consultant_id) references users;
alter table exams add constraint FKr1qm93flajdaclug2fg8i7bcg foreign key (course_id) references courses;
alter table groups add constraint FKt4nxc7036tu9ycukjeeo81qqi foreign key (classroom_id) references classrooms;
alter table groups_students add constraint FKpvecsvvd758a04vtjffrtvgcp foreign key (students_id) references users;
alter table groups_students add constraint FKhrg9h7qutffg03mof3hlfm5g7 foreign key (groups_id) references groups;
alter table student_option_answer_scores add constraint FKij39kbr9imvn002d5fw58sici foreign key (exam_question_option_answer_id) references exam_question_option_answers;
alter table student_option_answer_scores add constraint FK9ew8m5mo19xx0e90dgqltg6ob foreign key (student_id) references users;

    create table classrooms (
       id integer generated by default as identity,
        name varchar(50) not null,
        consultant_id integer,
        course_id integer,
        primary key (id)
    );

    create table classrooms_students (
       classrooms_id integer not null,
        students_id integer not null
    );

    create table courses (
       id integer generated by default as identity,
        credits double,
        name varchar(50) not null,
        degree_id integer,
        primary key (id)
    );

    create table degrees (
       id integer generated by default as identity,
        name varchar(50) not null,
        primary key (id)
    );

    create table exam_answers (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        finished boolean not null,
        exam_id integer not null,
        student_id integer not null,
        primary key (id)
    );

    create table exam_question_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        exam_answer_id integer not null,
        exam_question_id integer not null,
        primary key (id)
    );

    create table exam_question_option_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        is_selected boolean not null,
        exam_question_answer_id integer,
        exam_question_option_id integer,
        primary key (id)
    );

    create table exam_question_options (
       id integer generated by default as identity,
        is_rigth boolean not null,
        position integer,
        wording varchar(500) not null,
        exam_question_id integer,
        primary key (id)
    );

    create table exam_questions (
       id integer generated by default as identity,
        is_multiple_selection boolean not null,
        position integer,
        type varchar(25) not null,
        wording varchar(500) not null,
        exam_id integer,
        primary key (id)
    );

    create table exams (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        deadline date,
        instructions varchar(500),
        name varchar(50) not null,
        publication_date timestamp,
        type varchar(25) not null,
        consultant_id integer not null,
        course_id integer not null,
        primary key (id)
    );

    create table groups (
       id integer generated by default as identity,
        name varchar(50) not null,
        classroom_id integer,
        primary key (id)
    );

    create table groups_students (
       groups_id integer not null,
        students_id integer not null
    );

    create table student_option_answer_scores (
       exam_question_option_answer_id integer not null,
        student_id integer not null,
        score integer,
        primary key (exam_question_option_answer_id, student_id)
    );

    create table users (
       class varchar(31) not null,
        id integer generated by default as identity,
        dni varchar(9) not null,
        first_name varchar(50) not null,
        surname1 varchar(50),
        surname2 varchar(50),
        user_name varchar(50) not null,
        user_password varchar(50) not null,
        primary key (id)
    );

    alter table classrooms 
       add constraint FK7lbt0l1u0tdl3herl3wxin8vs 
       foreign key (consultant_id) 
       references users;

    alter table classrooms 
       add constraint FKptrcjflhvj48duhcag4f3x9j0 
       foreign key (course_id) 
       references courses;

    alter table classrooms_students 
       add constraint FK4qm2nt9roi9exg19i7ct4lyug 
       foreign key (students_id) 
       references users;

    alter table classrooms_students 
       add constraint FK1deyd4gk9oyhuq5715o9k2nfi 
       foreign key (classrooms_id) 
       references classrooms;

    alter table courses 
       add constraint FK1q2jh9x42qm5dspcsc6ux6rfe 
       foreign key (degree_id) 
       references degrees;

    alter table exam_answers 
       add constraint FKa5smxoto4oun5q5gffv7ly5yl 
       foreign key (exam_id) 
       references exams;

    alter table exam_answers 
       add constraint FK36fhn2x04ghokcj68si7iovhi 
       foreign key (student_id) 
       references users;

    alter table exam_question_answers 
       add constraint FKp9qast4xdo98rpy8mfg33djtg 
       foreign key (exam_answer_id) 
       references exam_answers;

    alter table exam_question_answers 
       add constraint FKax5lkfslgig12uhtorr1a3e9i 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_question_option_answers 
       add constraint FKhqr5lew83sp9g5d0752m9osmd 
       foreign key (exam_question_answer_id) 
       references exam_question_answers;

    alter table exam_question_option_answers 
       add constraint FKaoirvnctlkkhl0940vgvsurob 
       foreign key (exam_question_option_id) 
       references exam_question_options;

    alter table exam_question_options 
       add constraint FKn0j8vm7lf2vq9ie4q27046k4r 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_questions 
       add constraint FK5cd6sjmccb11rrwpyabyc81c0 
       foreign key (exam_id) 
       references exams;

    alter table exams 
       add constraint FKm3adut716bdwmb3w0qkwcdo2k 
       foreign key (consultant_id) 
       references users;

    alter table exams 
       add constraint FKr1qm93flajdaclug2fg8i7bcg 
       foreign key (course_id) 
       references courses;

    alter table groups 
       add constraint FKt4nxc7036tu9ycukjeeo81qqi 
       foreign key (classroom_id) 
       references classrooms;

    alter table groups_students 
       add constraint FKpvecsvvd758a04vtjffrtvgcp 
       foreign key (students_id) 
       references users;

    alter table groups_students 
       add constraint FKhrg9h7qutffg03mof3hlfm5g7 
       foreign key (groups_id) 
       references groups;

    alter table student_option_answer_scores 
       add constraint FKij39kbr9imvn002d5fw58sici 
       foreign key (exam_question_option_answer_id) 
       references exam_question_option_answers;

    alter table student_option_answer_scores 
       add constraint FK9ew8m5mo19xx0e90dgqltg6ob 
       foreign key (student_id) 
       references users;

    create table classrooms (
       id integer generated by default as identity,
        name varchar(50) not null,
        consultant_id integer,
        course_id integer,
        primary key (id)
    );

    create table classrooms_students (
       classrooms_id integer not null,
        students_id integer not null
    );

    create table courses (
       id integer generated by default as identity,
        credits double,
        name varchar(50) not null,
        degree_id integer,
        primary key (id)
    );

    create table degrees (
       id integer generated by default as identity,
        name varchar(50) not null,
        primary key (id)
    );

    create table exam_answers (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        finished boolean not null,
        exam_id integer not null,
        student_id integer not null,
        primary key (id)
    );

    create table exam_question_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        exam_answer_id integer not null,
        exam_question_id integer not null,
        primary key (id)
    );

    create table exam_question_option_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        is_selected boolean not null,
        exam_question_answer_id integer,
        exam_question_option_id integer,
        primary key (id)
    );

    create table exam_question_options (
       id integer generated by default as identity,
        is_rigth boolean not null,
        position integer,
        wording varchar(500) not null,
        exam_question_id integer,
        primary key (id)
    );

    create table exam_questions (
       id integer generated by default as identity,
        is_multiple_selection boolean not null,
        position integer,
        type varchar(25) not null,
        wording varchar(500) not null,
        exam_id integer,
        primary key (id)
    );

    create table exams (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        deadline date,
        instructions varchar(500),
        name varchar(50) not null,
        publication_date timestamp,
        type varchar(25) not null,
        consultant_id integer not null,
        course_id integer not null,
        primary key (id)
    );

    create table groups (
       id integer generated by default as identity,
        name varchar(50) not null,
        classroom_id integer,
        primary key (id)
    );

    create table groups_students (
       groups_id integer not null,
        students_id integer not null
    );

    create table student_option_answer_scores (
       exam_question_option_answer_id integer not null,
        student_id integer not null,
        score integer,
        primary key (exam_question_option_answer_id, student_id)
    );

    create table users (
       class varchar(31) not null,
        id integer generated by default as identity,
        dni varchar(9) not null,
        first_name varchar(50) not null,
        surname1 varchar(50),
        surname2 varchar(50),
        user_name varchar(50) not null,
        user_password varchar(50) not null,
        primary key (id)
    );

    alter table classrooms 
       add constraint FK7lbt0l1u0tdl3herl3wxin8vs 
       foreign key (consultant_id) 
       references users;

    alter table classrooms 
       add constraint FKptrcjflhvj48duhcag4f3x9j0 
       foreign key (course_id) 
       references courses;

    alter table classrooms_students 
       add constraint FK4qm2nt9roi9exg19i7ct4lyug 
       foreign key (students_id) 
       references users;

    alter table classrooms_students 
       add constraint FK1deyd4gk9oyhuq5715o9k2nfi 
       foreign key (classrooms_id) 
       references classrooms;

    alter table courses 
       add constraint FK1q2jh9x42qm5dspcsc6ux6rfe 
       foreign key (degree_id) 
       references degrees;

    alter table exam_answers 
       add constraint FKa5smxoto4oun5q5gffv7ly5yl 
       foreign key (exam_id) 
       references exams;

    alter table exam_answers 
       add constraint FK36fhn2x04ghokcj68si7iovhi 
       foreign key (student_id) 
       references users;

    alter table exam_question_answers 
       add constraint FKp9qast4xdo98rpy8mfg33djtg 
       foreign key (exam_answer_id) 
       references exam_answers;

    alter table exam_question_answers 
       add constraint FKax5lkfslgig12uhtorr1a3e9i 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_question_option_answers 
       add constraint FKhqr5lew83sp9g5d0752m9osmd 
       foreign key (exam_question_answer_id) 
       references exam_question_answers;

    alter table exam_question_option_answers 
       add constraint FKaoirvnctlkkhl0940vgvsurob 
       foreign key (exam_question_option_id) 
       references exam_question_options;

    alter table exam_question_options 
       add constraint FKn0j8vm7lf2vq9ie4q27046k4r 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_questions 
       add constraint FK5cd6sjmccb11rrwpyabyc81c0 
       foreign key (exam_id) 
       references exams;

    alter table exams 
       add constraint FKm3adut716bdwmb3w0qkwcdo2k 
       foreign key (consultant_id) 
       references users;

    alter table exams 
       add constraint FKr1qm93flajdaclug2fg8i7bcg 
       foreign key (course_id) 
       references courses;

    alter table groups 
       add constraint FKt4nxc7036tu9ycukjeeo81qqi 
       foreign key (classroom_id) 
       references classrooms;

    alter table groups_students 
       add constraint FKpvecsvvd758a04vtjffrtvgcp 
       foreign key (students_id) 
       references users;

    alter table groups_students 
       add constraint FKhrg9h7qutffg03mof3hlfm5g7 
       foreign key (groups_id) 
       references groups;

    alter table student_option_answer_scores 
       add constraint FKij39kbr9imvn002d5fw58sici 
       foreign key (exam_question_option_answer_id) 
       references exam_question_option_answers;

    alter table student_option_answer_scores 
       add constraint FK9ew8m5mo19xx0e90dgqltg6ob 
       foreign key (student_id) 
       references users;

    create table classrooms (
       id integer generated by default as identity,
        name varchar(50) not null,
        consultant_id integer,
        course_id integer,
        primary key (id)
    );

    create table classrooms_students (
       classrooms_id integer not null,
        students_id integer not null
    );

    create table courses (
       id integer generated by default as identity,
        credits double,
        name varchar(50) not null,
        degree_id integer,
        primary key (id)
    );

    create table degrees (
       id integer generated by default as identity,
        name varchar(50) not null,
        primary key (id)
    );

    create table exam_answers (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        finished boolean not null,
        exam_id integer not null,
        student_id integer not null,
        primary key (id)
    );

    create table exam_question_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        exam_answer_id integer not null,
        exam_question_id integer not null,
        primary key (id)
    );

    create table exam_question_option_answers (
       id integer generated by default as identity,
        answer varchar(4000) not null,
        is_selected boolean not null,
        exam_question_answer_id integer,
        exam_question_option_id integer,
        primary key (id)
    );

    create table exam_question_options (
       id integer generated by default as identity,
        is_rigth boolean not null,
        position integer,
        wording varchar(500) not null,
        exam_question_id integer,
        primary key (id)
    );

    create table exam_questions (
       id integer generated by default as identity,
        is_multiple_selection boolean not null,
        position integer,
        type varchar(25) not null,
        wording varchar(500) not null,
        exam_id integer,
        primary key (id)
    );

    create table exams (
       id integer generated by default as identity,
        change_date timestamp,
        creation_date date,
        deadline date,
        instructions varchar(500),
        name varchar(50) not null,
        publication_date timestamp,
        type varchar(25) not null,
        consultant_id integer not null,
        course_id integer not null,
        primary key (id)
    );

    create table groups (
       id integer generated by default as identity,
        name varchar(50) not null,
        classroom_id integer,
        primary key (id)
    );

    create table groups_students (
       groups_id integer not null,
        students_id integer not null
    );

    create table student_option_answer_scores (
       exam_question_option_answer_id integer not null,
        student_id integer not null,
        score integer,
        primary key (exam_question_option_answer_id, student_id)
    );

    create table users (
       class varchar(31) not null,
        id integer generated by default as identity,
        dni varchar(9) not null,
        first_name varchar(50) not null,
        surname1 varchar(50),
        surname2 varchar(50),
        user_name varchar(50) not null,
        user_password varchar(50) not null,
        primary key (id)
    );

    alter table classrooms 
       add constraint FK7lbt0l1u0tdl3herl3wxin8vs 
       foreign key (consultant_id) 
       references users;

    alter table classrooms 
       add constraint FKptrcjflhvj48duhcag4f3x9j0 
       foreign key (course_id) 
       references courses;

    alter table classrooms_students 
       add constraint FK4qm2nt9roi9exg19i7ct4lyug 
       foreign key (students_id) 
       references users;

    alter table classrooms_students 
       add constraint FK1deyd4gk9oyhuq5715o9k2nfi 
       foreign key (classrooms_id) 
       references classrooms;

    alter table courses 
       add constraint FK1q2jh9x42qm5dspcsc6ux6rfe 
       foreign key (degree_id) 
       references degrees;

    alter table exam_answers 
       add constraint FKa5smxoto4oun5q5gffv7ly5yl 
       foreign key (exam_id) 
       references exams;

    alter table exam_answers 
       add constraint FK36fhn2x04ghokcj68si7iovhi 
       foreign key (student_id) 
       references users;

    alter table exam_question_answers 
       add constraint FKp9qast4xdo98rpy8mfg33djtg 
       foreign key (exam_answer_id) 
       references exam_answers;

    alter table exam_question_answers 
       add constraint FKax5lkfslgig12uhtorr1a3e9i 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_question_option_answers 
       add constraint FKhqr5lew83sp9g5d0752m9osmd 
       foreign key (exam_question_answer_id) 
       references exam_question_answers;

    alter table exam_question_option_answers 
       add constraint FKaoirvnctlkkhl0940vgvsurob 
       foreign key (exam_question_option_id) 
       references exam_question_options;

    alter table exam_question_options 
       add constraint FKn0j8vm7lf2vq9ie4q27046k4r 
       foreign key (exam_question_id) 
       references exam_questions;

    alter table exam_questions 
       add constraint FK5cd6sjmccb11rrwpyabyc81c0 
       foreign key (exam_id) 
       references exams;

    alter table exams 
       add constraint FKm3adut716bdwmb3w0qkwcdo2k 
       foreign key (consultant_id) 
       references users;

    alter table exams 
       add constraint FKr1qm93flajdaclug2fg8i7bcg 
       foreign key (course_id) 
       references courses;

    alter table groups 
       add constraint FKt4nxc7036tu9ycukjeeo81qqi 
       foreign key (classroom_id) 
       references classrooms;

    alter table groups_students 
       add constraint FKpvecsvvd758a04vtjffrtvgcp 
       foreign key (students_id) 
       references users;

    alter table groups_students 
       add constraint FKhrg9h7qutffg03mof3hlfm5g7 
       foreign key (groups_id) 
       references groups;

    alter table student_option_answer_scores 
       add constraint FKij39kbr9imvn002d5fw58sici 
       foreign key (exam_question_option_answer_id) 
       references exam_question_option_answers;

    alter table student_option_answer_scores 
       add constraint FK9ew8m5mo19xx0e90dgqltg6ob 
       foreign key (student_id) 
       references users;
